### ISSUE TITLE
[AegiPersMo] [Feat. Request] Calculate org from center of mocha tracking plane

### ISSUE THREAD

**Issue by Ristellise** [Zahuczky/Zahuczkys-Aegisub-Scripts#1]

**Comment by Zahuczky** [comment]
https://github.com/Zahuczky/Zahuczkys-Aegisub-Scripts/commit/2dd648a8f02aad12a84fb780d40818b31681f76a
Added in above commit to daily branch, doesn't seem to work well with transforms. 
Example: https://files.catbox.moe/ufrksy.mp4
Might need more tweaking, but as of now, breaks everything that already works. 
Might be reopened later.
